version: '3.1'
services:
    itt:
      image: pwsh-wine
      build:
        context: docker
      volumes:
        - "./:/home/itt"
      working_dir: '/home/itt'
      command: ['pwsh', 'compile.ps1']